site_name: 身边的美食
site_description: 本地美食分享文档站
site_url: https://hnvfhp2211.github.io/food/

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest

plugins:
  - search
  - glightbox

nav:
  - 首页: index.md
  - 教师作品:
      - 鱼香茄子家常做法: 教师作品/鱼香茄子家常做法.md
  - 12班作业:
      - 1 周沛东: 班作品/12班/1周沛东.md
      - 2 蔡佳轩: 班作品/12班/2蔡佳轩.md
      - 3 罗雲瑞: 班作品/12班/3罗雲瑞.md
      - 4 朱瑞琪: 班作品/12班/4朱瑞琪.md
      - 5 杨玗依伶: 班作品/12班/5杨玗依伶.md
      - 7 朱宇涵: 班作品/12班/7朱宇涵.md
      - 9 陈映汝: 班作品/12班/9陈映汝.md
      - 12 黄钰茜: 班作品/12班/12黄钰茜.md
      - 13 胡玉科: 班作品/12班/13胡玉科.md
      - 14 资可馨: 班作品/12班/14资可馨.md
      - 15 曾意茹: 班作品/12班/15曾意茹.md
      - 17 范丽娟: 班作品/12班/17范丽娟.md
      - 19 程沛雯: 班作品/12班/19程沛雯.md
      - 20 漆杰瑞: 班作品/12班/20漆杰瑞.md
      - 22 曾廉森: 班作品/12班/22曾廉森.md
      - 23 孙萌: 班作品/12班/23孙萌.md
      - 25 谭皓元: 班作品/12班/25谭皓元.md
      - 26 祝艺阳: 班作品/12班/26祝艺阳.md
      - 27 刘知行: 班作品/12班/27刘知行.md
      - 28 吴梦婷: 班作品/12班/28吴梦婷.md
      - 30 龚玲珑: 班作品/12班/30龚玲珑.md
      - 31 胡翔瑞: 班作品/12班/31胡翔瑞.md
      - 32 袁艺菡: 班作品/12班/32袁艺菡.md
      - 33 吴俊南: 班作品/12班/33吴俊南.md
      - 35 李思翰: 班作品/12班/35李思翰.md
      - 36 马宜琳: 班作品/12班/36马宜琳.md
      - 39 刘雨泽: 班作品/12班/39刘雨泽.md
      - 42 王彦茜: 班作品/12班/42王彦茜.md
      - 43 黄逸潇: 班作品/12班/43黄逸潇.md
      - 44 范子娢: 班作品/12班/44范子娢.md
      - 46 林科宇: 班作品/12班/46林科宇.md
      - 48 宋炫余: 班作品/12班/48宋炫余.md
      - 50 周斗量: 班作品/12班/50周斗量.md
      - 51 宋锦泓: 班作品/12班/51宋锦泓.md
      - 52 刘焰东: 班作品/12班/52刘焰东.md
      - 54 吴辰羲: 班作品/12班/54吴辰羲.md
      - 55 孟钰烨: 班作品/12班/55孟钰烨.md
  - 6班作业:
      - 1 左海琪: 班作品/6班/1左海琪.md
      - 2 张子序: 班作品/6班/2张子序.md
      - 3 张诗诗: 班作品/6班/3张诗诗.md
      - 4 曾逸豪: 班作品/6班/4曾逸豪.md
      - 5 胡歆玥: 班作品/6班/5胡歆玥.md
      - 6 高宇翰: 班作品/6班/6高宇翰.md
      - 7 夏斯琪: 班作品/6班/7夏斯琪.md
      - 8 龚舒雨: 班作品/6班/8龚舒雨.md
      - 9 窦榆翔: 班作品/6班/9窦榆翔.md
      - 10 梁芮燕: 班作品/6班/10梁芮燕.md
      - 11 汤涛: 班作品/6班/11汤涛.md
      - 12 董语晨: 班作品/6班/12董语晨.md
      - 13 刘佳林: 班作品/6班/13刘佳林.md
      - 14 宁逸欣: 班作品/6班/14宁逸欣.md
      - 16 陈思怡: 班作品/6班/16陈思怡.md
      - 17 曾宇馨: 班作品/6班/17曾宇馨.md
      - 18 卢涵羿: 班作品/6班/18卢涵羿.md
      - 20 阮钰洁: 班作品/6班/20阮钰洁.md
      - 21 曾渝雯: 班作品/6班/21曾渝雯.md
      - 22 曾梓琦: 班作品/6班/22曾梓琦.md
      - 23 陈映希: 班作品/6班/23陈映希.md
      - 24 左旭利: 班作品/6班/24左旭利.md
      - 25 税裕杰: 班作品/6班/25税裕杰.md
      - 26 王可昕: 班作品/6班/26王可昕.md
      - 28 王欣瑞: 班作品/6班/28王欣瑞.md
      - 30 林雨佳: 班作品/6班/30林雨佳.md
      - 31 王梓浠: 班作品/6班/31王梓浠.md
      - 32 贾贻斐: 班作品/6班/32贾贻斐.md
      - 34 钟茜: 班作品/6班/34钟茜.md
      - 38 胡诗涵: 班作品/6班/38胡诗涵.md
      - 39 郭瑾坤: 班作品/6班/39郭瑾坤.md
      - 41 杨梓宸: 班作品/6班/41杨梓宸.md
      - 42 廖雨萱: 班作品/6班/42廖雨萱.md
      - 43 周欣怡: 班作品/6班/43周欣怡.md
      - 44 尹舒杭: 班作品/6班/44尹舒杭.md
      - 45 罗安宇: 班作品/6班/45罗安宇.md
      - 46 熊宇晨: 班作品/6班/46熊宇晨.md
      - 48 罗旭: 班作品/6班/48罗旭.md
      - 55 曾暄玥: 班作品/6班/55曾暄玥.md
  - 11班作业:
      - 1 范奕瑶: 班作品/11班/1范奕瑶.md
      - 2 周俊峰: 班作品/11班/2周俊峰.md
      - 3 王子萱: 班作品/11班/3王子萱.md
      - 4 周星璐: 班作品/11班/4周星璐.md
      - 5 卫治宇: 班作品/11班/5卫治宇.md
      - 6 张家漆: 班作品/11班/6张家漆.md
      - 7 左芮亭: 班作品/11班/7左芮亭.md
      - 8 陈雨彤: 班作品/11班/8陈雨彤.md
      - 9 卢宇晨: 班作品/11班/9卢宇晨.md
      - 10 漆雅馨: 班作品/11班/10漆雅馨.md
      - 11 文彦博: 班作品/11班/11文彦博.md
      - 13 李忆晗: 班作品/11班/13李忆晗.md
      - 14 付波: 班作品/11班/14付波.md
      - 16 王宇泽: 班作品/11班/16王宇泽.md
      - 17 陈鑫淼: 班作品/11班/17陈鑫淼.md
      - 18 刘家瑞: 班作品/11班/18刘家瑞.md
      - 19 吴恩熙: 班作品/11班/19吴恩熙.md
      - 20 朱虹蓁: 班作品/11班/20朱虹蓁.md
      - 21 熊婧妤: 班作品/11班/21熊婧妤.md
      - 22 易子扬: 班作品/11班/22易子扬.md
      - 23 王歆颐: 班作品/11班/23王歆颐.md
      - 25 李卫晨: 班作品/11班/25李卫晨.md
      - 26 黎妍欣: 班作品/11班/26黎妍欣.md
      - 27 胡浩逸: 班作品/11班/27胡浩逸.md
      - 29 曾榆轲: 班作品/11班/29曾榆轲.md
      - 30 鄢梓钰: 班作品/11班/30鄢梓钰.md
      - 31 钟直楷: 班作品/11班/31钟直楷.md
      - 32 曾雨晨: 班作品/11班/32曾雨晨.md
      - 33 詹曼依: 班作品/11班/33詹曼依.md
      - 34 龚宇轩: 班作品/11班/34龚宇轩.md
      - 35 谭雨其: 班作品/11班/35谭雨其.md
      - 36 吴沛颖: 班作品/11班/36吴沛颖.md
      - 37 邓雅琪: 班作品/11班/37邓雅琪.md
      - 38 雷程希: 班作品/11班/38雷程希.md
      - 39 郭文涛: 班作品/11班/39郭文涛.md
      - 40 侯俊伊: 班作品/11班/40侯俊伊.md
      - 42 丁彦岭: 班作品/11班/42丁彦岭.md
      - 44 廖梦菡: 班作品/11班/44廖梦菡.md
      - 45 周欣媛: 班作品/11班/45周欣媛.md
      - 24 陈晏瑶: 班作品/11班/24陈晏瑶.md
      - 51 周新雅: 班作品/11班/51周新雅.md
      - 12 刘烯晨: 班作品/11班/12刘烯晨.md
      - 15 雷思媛: 班作品/11班/15雷思媛.md
  - 4班作业:
      - 1 孙梁桓: 班作品/4班/1孙梁桓.md
      - 2 龙星宇: 班作品/4班/2龙星宇.md
      - 4 廖雨泽: 班作品/4班/4廖雨泽.md
      - 6 唐澜芯: 班作品/4班/6唐澜芯.md
      - 8 徐铭应: 班作品/4班/8徐铭应.md
      - 9 刘雨萱: 班作品/4班/9刘雨萱.md
      - 10 邱政滔: 班作品/4班/10邱政滔.md
      - 13 梁雲熙: 班作品/4班/13梁雲熙.md
      - 14 朱天雨: 班作品/4班/14朱天雨.md
      - 15 李莘芮: 班作品/4班/15李莘芮.md
      - 16 王应历: 班作品/4班/16王应历.md
      - 17 张誉锌: 班作品/4班/17张誉锌.md
      - 18 李婷婷: 班作品/4班/18李婷婷.md
      - 19 熊汐越: 班作品/4班/19熊汐越.md
      - 20 汤含笑: 班作品/4班/20汤含笑.md
      - 21 刘恩熙: 班作品/4班/21刘恩熙.md
      - 22 唐敬: 班作品/4班/22唐敬.md
      - 24 卢诗瑞: 班作品/4班/24卢诗瑞.md
      - 25 贺欣怡: 班作品/4班/25贺欣怡.md
      - 26 曾莅雯: 班作品/4班/26曾莅雯.md
      - 27 卢晨汐: 班作品/4班/27卢晨汐.md
      - 28 曾荣意: 班作品/4班/28曾荣意.md
      - 29 李堃博: 班作品/4班/29李堃博.md
      - 30 徐梓心: 班作品/4班/30徐梓心.md
      - 31 廖若伊: 班作品/4班/31廖若伊.md
      - 33 胡绘: 班作品/4班/33胡绘.md
      - 34 宋志强: 班作品/4班/34宋志强.md
      - 39 金思汛: 班作品/4班/39金思汛.md
      - 40 李惠静: 班作品/4班/40李惠静.md
      - 41 陈澐斯: 班作品/4班/41陈澐斯.md
      - 44 周梓艺: 班作品/4班/44周梓艺.md
      - 49 王梓菡: 班作品/4班/49王梓菡.md
      - 5陈奕竹: 班作品/4班/5陈奕竹.md
  - 3班作业:
      - 1 王嘉鑫: 班作品/3班/1王嘉鑫.md
      - 2 吴丽嘉: 班作品/3班/2吴丽嘉.md
      - 3 吴思翰: 班作品/3班/3吴思翰.md
      - 4 曾琬凌: 班作品/3班/4曾琬凌.md
      - 5 王志宇: 班作品/3班/5王志宇.md
      - 6 石家维: 班作品/3班/6石家维.md
      - 7 彭椿杰: 班作品/3班/7彭椿杰.md
      - 8 罗丹伶: 班作品/3班/8罗丹伶.md
      - 9 陈仔涵: 班作品/3班/9陈仔涵.md
      - 15 卢科宇: 班作品/3班/15卢科宇.md
      - 10 刘宇珊: 班作品/3班/10刘宇珊.md
      - 11 宋鹏洁: 班作品/3班/11宋鹏洁.md
      - 12 唐铭: 班作品/3班/12唐铭.md
      - 14 张楷彬: 班作品/3班/14张楷彬.md
      - 16 林佳慧: 班作品/3班/16林佳慧.md
      - 17 杨思若: 班作品/3班/17杨思若.md
      - 18 李玉龙: 班作品/3班/18李玉龙.md
      - 19 苏慧语: 班作品/3班/19苏慧语.md
      - 20 袁晨博: 班作品/3班/20袁晨博.md
      - 21 夏诗蕊: 班作品/3班/21夏诗蕊.md
      - 22 刘俊熙: 班作品/3班/22刘俊熙.md
      - 23 王伊萱: 班作品/3班/23王伊萱.md
      - 24 陈雨涵: 班作品/3班/24陈雨涵.md
      - 25 王殿尧: 班作品/3班/25王殿尧.md
      - 26 漆思瑞: 班作品/3班/26漆思瑞.md
      - 28 周语心: 班作品/3班/28周语心.md
      - 29 袁文峻: 班作品/3班/29袁文峻.md
      - 30 廖曼珺: 班作品/3班/30廖曼珺.md
      - 31 朱航宇: 班作品/3班/31朱航宇.md
      - 32 刘弈淳: 班作品/3班/32刘弈淳.md
      - 34 方怡馨: 班作品/3班/34方怡馨.md
      - 35 夏宇航: 班作品/3班/35夏宇航.md
      - 36 龙浩宇: 班作品/3班/36龙浩宇.md
      - 37 谭程峻: 班作品/3班/37谭程峻.md
      - 38 税景桥: 班作品/3班/38税景桥.md
      - 39 左惜瑗: 班作品/3班/39左惜瑗.md
      - 40 刘佳鑫: 班作品/3班/40刘佳鑫.md
      - 41 宋泉霖: 班作品/3班/41宋泉霖.md
      - 42 罗紫欣: 班作品/3班/42罗紫欣.md
      - 43 方译冉: 班作品/3班/43方译冉.md
      - 44 李泉霖: 班作品/3班/44李泉霖.md
      - 45 税泓友: 班作品/3班/45税泓友.md
      - 46 黄才娣: 班作品/3班/46黄才娣.md
      - 47 刘芮希: 班作品/3班/47刘芮希.md
      - 48 熊恩乙: 班作品/3班/48熊恩乙.md
      - 49 李玥辰: 班作品/3班/49李玥辰.md
      - 51 冯晨: 班作品/3班/51冯晨.md
      - 52 刘洋希: 班作品/3班/52刘洋希.md
      - 55 王钟佳: 班作品/3班/55王钟佳.md